projects:
  app:
    schemaPath: src/schema.graphql
    includes:
    - "src/schema.graphql"
    - "src/generated/prisma.graphql"
    extensions:
      endpoints:
        default: http://localhost:3000/graphql
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
  
  
