version: '3'
services:
  app:
    depends_on:
    - prisma
    restart: always
    build:
      dockerfile: ./node_modules/@etidbury/ts-gql-helpers/config/Dockerfile
      # dockerfile: ./Dockerfile
      context: ./
      args:
        PORT: ${PORT}
    ports:
    - "${PORT}:${PORT}"
  prisma:
    depends_on:
    - mysql
    restart: always
    build:
      dockerfile: ../node_modules/@etidbury/ts-gql-helpers/prisma/Dockerfile
      context: ./database
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        PRISMA_MANAGEMENT_API_SECRET: ${PRISMA_MANAGEMENT_API_SECRET}
    ports:
    - "4466:4466"
    # environment:
    #   - MYSQL_DATABASE='db-local'
    #   - MYSQL_HOST='localhost'
    #   - MYSQL_USER='root'
    #   - MYSQL_PASSWORD='prisma'
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
