version: '3'
services:
  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.19
    restart: always
    ports:
    - "4466:4466"
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: localhost
            port: 3306
            user: root
            password: prisma
            migrations: true
            rawAccess: true
  mysql:
    ports:
    - "3306:3306"
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  mysql:
